name: Coakley House Bahamas
favicon: null
layout_spectrum: 0.7201759165618569
typography_spectrum: 0.8928903804626316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8840470577124506
  lightness: 0.3642907945904881
  saturation: 0.36180929094552994
  rhythmicContrast: 0.3749104111921042
purpose: []
