name: Coakley House Bahamas
favicon: null
layout_spectrum: 0.25038
typography_spectrum: 0.2993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96c6ec'
    - '#5995db'
    - '#000800'
    - '#292a24'
    - '#406a76'
  brandStrength: 0.8840470577124506
  lightness: 0.3642907945904881
  saturation: 0.36180929094552994
  rhythmicContrast: 0.3749104111921042
purpose: []
